# This is a basic workflow to help you get started with Actions

name: scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  checks: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  scan-with-dastardly:
    name: Scan with Dastardly
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@main
        with: 
          target-url: 'https://app.shadowhq.io/'
           
      - name: Publish Dastardly Scan Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          check_name: 'Dastardly Scan Report'
          report_paths: '**/dastardly-report.xml'
          require_tests: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      
